# -*- encoding : utf-8 -*-
TINYMCE_OPTIONS = { :theme => 'advanced',
:browsers => %w{msie gecko safari},   
:theme_advanced_layout_manager => "SimpleLayout",
:theme_advanced_statusbar_location => "bottom",
:theme_advanced_toolbar_location => "top",
:theme_advanced_toolbar_align => "left",
:theme_advanced_resizing => true,
:relative_urls => false,
:convert_urls => false,
:cleanup => true,
:cleanup_on_startup => true,  
:convert_fonts_to_spans => true,
:theme_advanced_resize_horizontal => false,
:theme_advanced_buttons1 => ["undo,redo,|,cut,copy,paste,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,link,unlink,|,image,media,|,code"],
:theme_advanced_buttons2 => [],
:language => :zh,
:plugins => %w{contextmenu media advimage paste fullscreen} }
